# Generated by Django 5.0.1 on 2025-08-12 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('password_hash', models.CharField(blank=True, max_length=255)),
                ('lock_timeout', models.IntegerField(default=300)),
                ('auto_lock', models.BooleanField(default=True)),
                ('require_on_startup', models.BooleanField(default=False)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_locked', models.DateTimeField(blank=True, null=True)),
                ('last_unlocked', models.DateTimeField(blank=True, null=True)),
                ('max_failed_attempts', models.IntegerField(default=5)),
                ('lockout_duration', models.IntegerField(default=300)),
                ('require_password_change', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screen_lock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Screen Lock',
                'verbose_name_plural': 'Screen Locks',
            },
        ),
    ]
