# Generated by Django 5.0.1 on 2025-08-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_screenlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenlock',
            name='is_currently_locked',
            field=models.BooleanField(default=False),
        ),
    ]
