# Generated by Django 5.0.1 on 2025-08-12 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_screenlock_is_currently_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenlock',
            name='is_currently_locked',
        ),
    ]
