# Generated by Django 5.0.1 on 2025-08-07 15:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('recording_path', models.CharField(default='/media/cctv/recordings', help_text='path for storing recordings', max_length=500)),
                ('snapshot_path', models.CharField(default='/media/cctv/snapshots', help_text='path for storing snapshots', max_length=500)),
                ('max_storage_gb', models.IntegerField(default=100, help_text='maximum storage in gb', validators=[django.core.validators.MinValueValidator(1)])),
                ('warning_threshold_percent', models.IntegerField(default=80, help_text='warning when storage reaches this percentage', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('default_retention_days', models.IntegerField(default=7, help_text='default days to keep recordings', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('auto_delete_old', models.BooleanField(default=True, help_text='automatically delete old recordings')),
                ('current_usage_gb', models.FloatField(default=0.0)),
                ('last_cleanup', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='camera display name', max_length=100)),
                ('model', models.CharField(choices=[('tapo_c200', 'tp-link tapo c200'), ('tapo_c210', 'tp-link tapo c210'), ('tapo_c310', 'tp-link tapo c310'), ('tapo_c320ws', 'tp-link tapo c320ws'), ('generic_rtsp', 'generic rtsp camera'), ('onvif', 'onvif compatible')], default='tapo_c200', max_length=50)),
                ('location', models.CharField(help_text='physical location', max_length=200)),
                ('description', models.TextField(blank=True, help_text='additional notes')),
                ('ip_address', models.GenericIPAddressField(help_text='camera ip address')),
                ('port', models.IntegerField(default=554, help_text='rtsp/http port (default: 554 for rtsp)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('protocol', models.CharField(choices=[('rtsp', 'rtsp'), ('http', 'http'), ('https', 'https'), ('onvif', 'onvif')], default='rtsp', max_length=10)),
                ('stream_path', models.CharField(default='/stream1', help_text='stream path (e.g., /stream1 for main, /stream2 for sub)', max_length=200)),
                ('username', models.CharField(help_text='camera username', max_length=100)),
                ('password', models.CharField(help_text='camera password (encrypted in production)', max_length=100)),
                ('status', models.CharField(choices=[('online', 'online'), ('offline', 'offline'), ('recording', 'recording'), ('error', 'error'), ('maintenance', 'maintenance')], default='offline', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='camera enabled/disabled')),
                ('recording_enabled', models.BooleanField(default=False, help_text='continuous recording')),
                ('motion_detection', models.BooleanField(default=True, help_text='motion detection enabled')),
                ('audio_enabled', models.BooleanField(default=False, help_text='audio recording enabled')),
                ('resolution', models.CharField(default='1920x1080', help_text='video resolution', max_length=20)),
                ('fps', models.IntegerField(default=25, help_text='frames per second', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('bitrate', models.IntegerField(default=2048, help_text='video bitrate in kbps', validators=[django.core.validators.MinValueValidator(128), django.core.validators.MaxValueValidator(8192)])),
                ('has_ptz', models.BooleanField(default=False, help_text='camera has ptz controls')),
                ('ptz_preset_positions', models.JSONField(blank=True, default=dict, help_text='saved ptz positions')),
                ('kerberos_enabled', models.BooleanField(default=False, help_text='use kerberos.io for processing')),
                ('kerberos_url', models.URLField(blank=True, help_text='kerberos instance url')),
                ('kerberos_key', models.CharField(blank=True, help_text='kerberos api key', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen', models.DateTimeField(blank=True, help_text='last successful connection', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['location', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('motion', 'motion detected'), ('sound', 'sound detected'), ('person', 'person detected'), ('vehicle', 'vehicle detected'), ('animal', 'animal detected'), ('package', 'package detected'), ('tampering', 'camera tampering'), ('connection_lost', 'connection lost'), ('storage_full', 'storage full'), ('system', 'system alert')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('critical', 'critical')], default='medium', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(help_text='alert description')),
                ('image_path', models.FilePathField(blank=True, help_text='snapshot at alert time', path='/media/cctv/alerts')),
                ('video_clip_path', models.FilePathField(blank=True, help_text='short video clip of event', path='/media/cctv/alerts')),
                ('confidence_score', models.FloatField(blank=True, help_text='ai detection confidence (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('detection_data', models.JSONField(blank=True, default=dict, help_text='additional detection metadata')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cctv_alerts', to=settings.AUTH_USER_MODEL)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='cctv.camera')),
            ],
            options={
                'ordering': ['-timestamp', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='CameraGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('grid_layout', models.CharField(default='2x2', help_text='grid layout (e.g., 2x2, 3x3, 4x4)', max_length=10)),
                ('auto_cycle', models.BooleanField(default=False, help_text='auto cycle through cameras')),
                ('cycle_interval', models.IntegerField(default=10, help_text='seconds between camera switches', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(300)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cameras', models.ManyToManyField(related_name='groups', to='cctv.camera')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CameraStream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quality', models.CharField(choices=[('main', 'main stream (high quality)'), ('sub', 'sub stream (low quality)'), ('mobile', 'mobile stream (optimized)')], default='main', max_length=20)),
                ('protocol', models.CharField(choices=[('rtsp', 'rtsp'), ('rtmp', 'rtmp'), ('hls', 'hls'), ('webrtc', 'webrtc')], default='rtsp', max_length=20)),
                ('stream_url', models.TextField(help_text='full stream url')),
                ('is_active', models.BooleanField(default=True)),
                ('resolution', models.CharField(default='1920x1080', max_length=20)),
                ('fps', models.IntegerField(default=25)),
                ('bitrate', models.IntegerField(default=2048, help_text='kbps')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='cctv.camera')),
            ],
            options={
                'ordering': ['camera', 'quality'],
            },
        ),
        migrations.CreateModel(
            name='RecordingSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='schedule name', max_length=100)),
                ('days_of_week', models.JSONField(default=list, help_text='days when recording is active (list of integers 0-6)')),
                ('start_time', models.TimeField(help_text='daily start time')),
                ('end_time', models.TimeField(help_text='daily end time')),
                ('is_active', models.BooleanField(default=True)),
                ('recording_quality', models.CharField(choices=[('main', 'high quality'), ('sub', 'low quality')], default='main', max_length=20)),
                ('motion_only', models.BooleanField(default=False, help_text='record only on motion')),
                ('retention_days', models.IntegerField(default=7, help_text='days to keep recordings', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='cctv.camera')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['camera', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='RecordingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recording_type', models.CharField(choices=[('continuous', 'continuous'), ('motion', 'motion triggered'), ('manual', 'manual'), ('scheduled', 'scheduled'), ('alert', 'alert triggered')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('recording', 'recording'), ('completed', 'completed'), ('failed', 'failed'), ('processing', 'processing')], default='scheduled', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='duration in seconds', null=True)),
                ('file_path', models.FilePathField(blank=True, help_text='recording file path', path='/media/cctv/recordings')),
                ('file_size', models.BigIntegerField(blank=True, help_text='file size in bytes', null=True)),
                ('thumbnail_path', models.FilePathField(blank=True, help_text='thumbnail image path', path='/media/cctv/thumbnails')),
                ('video_codec', models.CharField(default='h264', max_length=50)),
                ('audio_codec', models.CharField(blank=True, max_length=50)),
                ('resolution', models.CharField(blank=True, max_length=20)),
                ('fps', models.IntegerField(blank=True, null=True)),
                ('motion_events', models.IntegerField(default=0, help_text='number of motion events detected')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='cctv.camera')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['user', 'is_active'], name='cctv_camera_user_id_264f16_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['status'], name='cctv_camera_status_fa531e_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['camera', 'timestamp'], name='cctv_alert_camera__d38201_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', 'is_resolved'], name='cctv_alert_alert_t_ed2bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['priority', 'is_resolved'], name='cctv_alert_priorit_e9ea02_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cameragroup',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='camerastream',
            unique_together={('camera', 'quality')},
        ),
        migrations.AddIndex(
            model_name='recordingsession',
            index=models.Index(fields=['camera', 'start_time'], name='cctv_record_camera__661a18_idx'),
        ),
        migrations.AddIndex(
            model_name='recordingsession',
            index=models.Index(fields=['status'], name='cctv_record_status_fcffcb_idx'),
        ),
        migrations.AddIndex(
            model_name='recordingsession',
            index=models.Index(fields=['recording_type'], name='cctv_record_recordi_e8fd97_idx'),
        ),
    ]
