# Generated by Django 5.0.1 on 2025-08-09 05:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.CharField(max_length=100)),
                ('commit_hash', models.CharField(max_length=40)),
                ('commit_message', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('modified_files', models.JSONField(default=list)),
                ('untracked_files', models.JSONField(default=list)),
                ('staged_files', models.JSONField(default=list)),
                ('has_changes', models.BooleanField(default=False)),
                ('ahead_count', models.IntegerField(default=0)),
                ('behind_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Git Status',
                'verbose_name_plural': 'Git Statuses',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_archives', models.IntegerField(default=0)),
                ('total_size_bytes', models.BigIntegerField(default=0)),
                ('total_size_gb', models.FloatField(default=0.0)),
                ('average_size_mb', models.FloatField(default=0.0)),
                ('anomaly_count', models.IntegerField(default=0)),
                ('progress_percent', models.IntegerField(default=0)),
                ('current_archive', models.CharField(blank=True, max_length=100)),
                ('status_message', models.CharField(blank=True, max_length=200)),
                ('is_complete', models.BooleanField(default=False)),
                ('has_errors', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scan Session',
                'verbose_name_plural': 'Scan Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='VersionArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(db_index=True, max_length=20, unique=True)),
                ('path', models.CharField(max_length=500)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('size_mb', models.FloatField(default=0.0)),
                ('file_count', models.IntegerField(default=0)),
                ('directory_count', models.IntegerField(default=0)),
                ('z_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('large', 'Large (50-200 MB)'), ('very_large', 'Very Large (200-500 MB)'), ('huge', 'Huge (500+ MB)')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_scanned', models.DateTimeField(auto_now=True)),
                ('git_commit', models.CharField(blank=True, max_length=40, null=True)),
                ('git_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('git_tag', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Version Archive',
                'verbose_name_plural': 'Version Archives',
                'ordering': ['-version'],
                'indexes': [models.Index(fields=['version'], name='version_man_version_e4ab53_idx'), models.Index(fields=['size_mb'], name='version_man_size_mb_0fd933_idx'), models.Index(fields=['status'], name='version_man_status_0ffa8a_idx'), models.Index(fields=['is_anomaly'], name='version_man_is_anom_9d9dfc_idx')],
            },
        ),
    ]
