# Generated by Django 5.0.1 on 2025-08-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionarchive',
            name='status',
            field=models.CharField(choices=[('normal', 'normal'), ('large', 'large (50-200 mb)'), ('very_large', 'very large (200-500 mb)'), ('huge', 'huge (500+ mb)')], default='normal', max_length=20),
        ),
    ]
