# Generated by Django 5.0.1 on 2025-08-27 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_remove_screenlock_is_currently_locked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecariaMailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('mailbox_created', models.BooleanField(default=False)),
                ('mailbox_size_mb', models.IntegerField(default=1024)),
                ('password_set', models.BooleanField(default=False)),
                ('imap_enabled', models.BooleanField(default=True)),
                ('pop3_enabled', models.BooleanField(default=False)),
                ('smtp_enabled', models.BooleanField(default=True)),
                ('daily_send_limit', models.IntegerField(default=500)),
                ('attachment_size_limit_mb', models.IntegerField(default=25)),
                ('auto_responder_enabled', models.BooleanField(default=False)),
                ('auto_responder_message', models.TextField(blank=True)),
                ('forwarding_enabled', models.BooleanField(default=False)),
                ('forwarding_address', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('suspended_reason', models.TextField(blank=True)),
                ('messages_sent', models.IntegerField(default=0)),
                ('messages_received', models.IntegerField(default=0)),
                ('current_usage_mb', models.FloatField(default=0)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recaria_mailbox', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'recaria.org mailbox',
                'verbose_name_plural': 'recaria.org mailboxes',
                'ordering': ['email_address'],
            },
        ),
    ]
