# Generated by Django 5.0.1 on 2025-08-12 00:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('private', 'private'), ('friends', 'friends only'), ('public', 'public')], default='private', max_length=20)),
                ('cover_image', models.URLField(blank=True, max_length=500)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags')),
                ('view_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='movies_genr_slug_a56002_idx')],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tmdb_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('imdb_id', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('original_title', models.CharField(blank=True, max_length=500)),
                ('content_type', models.CharField(choices=[('movie', 'movie'), ('series', 'tv series'), ('documentary', 'documentary'), ('anime', 'anime')], db_index=True, default='movie', max_length=20)),
                ('overview', models.TextField(blank=True)),
                ('tagline', models.CharField(blank=True, max_length=500)),
                ('release_date', models.DateField(blank=True, db_index=True, null=True)),
                ('runtime', models.IntegerField(blank=True, help_text='Runtime in minutes', null=True)),
                ('status', models.CharField(choices=[('released', 'released'), ('upcoming', 'upcoming'), ('in_production', 'in production'), ('cancelled', 'cancelled')], default='released', max_length=20)),
                ('poster_path', models.URLField(blank=True, max_length=500)),
                ('backdrop_path', models.URLField(blank=True, max_length=500)),
                ('trailer_url', models.URLField(blank=True, max_length=500)),
                ('production_companies', models.JSONField(blank=True, default=list, help_text='List of production companies')),
                ('production_countries', models.JSONField(blank=True, default=list, help_text='List of production countries')),
                ('spoken_languages', models.JSONField(blank=True, default=list, help_text='List of spoken languages')),
                ('budget', models.BigIntegerField(blank=True, null=True)),
                ('revenue', models.BigIntegerField(blank=True, null=True)),
                ('tmdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('tmdb_vote_count', models.IntegerField(default=0)),
                ('popularity', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('number_of_seasons', models.IntegerField(blank=True, null=True)),
                ('number_of_episodes', models.IntegerField(blank=True, null=True)),
                ('episode_runtime', models.JSONField(blank=True, default=list, help_text='For series: typical episode runtime in minutes')),
                ('api_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_api_sync', models.DateTimeField(blank=True, null=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='movies.genre')),
            ],
            options={
                'verbose_name': 'movie/series',
                'verbose_name_plural': 'movies/series',
                'ordering': ['-popularity', '-release_date'],
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.collection')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
            options={
                'ordering': ['position', 'added_at'],
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='movies',
            field=models.ManyToManyField(related_name='collections', through='movies.CollectionItem', to='movies.movie'),
        ),
        migrations.CreateModel(
            name='PersonalArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('digital', 'Digital'), ('bluray', 'Blu-ray'), ('dvd', 'DVD'), ('vhs', 'VHS'), ('streaming', 'Streaming Service')], max_length=20)),
                ('quality', models.CharField(blank=True, choices=[('4k', '4K Ultra HD'), ('1080p', '1080p Full HD'), ('720p', '720p HD'), ('dvd', 'DVD Quality'), ('other', 'Other')], max_length=20, null=True)),
                ('location', models.CharField(blank=True, help_text='Physical or digital location', max_length=500)),
                ('file_size_gb', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('subtitles', models.JSONField(blank=True, default=list, help_text='Available subtitle languages')),
                ('audio_languages', models.JSONField(blank=True, default=list, help_text='Available audio languages')),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags')),
                ('acquired_date', models.DateField(default=django.utils.timezone.now)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_by', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_archive', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(10.0)])),
                ('review_title', models.CharField(blank=True, max_length=200)),
                ('review_text', models.TextField(blank=True)),
                ('contains_spoilers', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('helpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('progress_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('season', models.IntegerField(blank=True, null=True)),
                ('episode', models.IntegerField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_sessions', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('want_to_watch', 'want to watch'), ('watching', 'currently watching'), ('watched', 'watched'), ('dropped', 'dropped'), ('on_hold', 'on hold')], db_index=True, default='want_to_watch', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'low priority'), ('medium', 'medium priority'), ('high', 'high priority'), ('urgent', 'must watch')], default='medium', max_length=20)),
                ('current_season', models.IntegerField(blank=True, null=True)),
                ('current_episode', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('watched_at', models.DateTimeField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlisted_by', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-added_at'],
            },
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title', 'release_date'], name='movies_movi_title_20a8c3_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['content_type', '-popularity'], name='movies_movi_content_8fc5bc_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-created_at'], name='movies_movi_created_2750ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collectionitem',
            unique_together={('collection', 'movie')},
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['user', '-updated_at'], name='movies_coll_user_id_7f8850_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['visibility', '-created_at'], name='movies_coll_visibil_ac6500_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='personalarchive',
            index=models.Index(fields=['user', '-added_at'], name='movies_pers_user_id_45bdb9_idx'),
        ),
        migrations.AddIndex(
            model_name='personalarchive',
            index=models.Index(fields=['format', 'quality'], name='movies_pers_format_e9971c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='personalarchive',
            unique_together={('user', 'movie', 'format')},
        ),
        migrations.AddIndex(
            model_name='userrating',
            index=models.Index(fields=['user', '-created_at'], name='movies_user_user_id_ba5c70_idx'),
        ),
        migrations.AddIndex(
            model_name='userrating',
            index=models.Index(fields=['movie', '-rating'], name='movies_user_movie_i_e0877b_idx'),
        ),
        migrations.AddIndex(
            model_name='userrating',
            index=models.Index(fields=['is_public', '-helpful_count'], name='movies_user_is_publ_cca331_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together={('user', 'movie')},
        ),
        migrations.AddIndex(
            model_name='watchhistory',
            index=models.Index(fields=['user', '-started_at'], name='movies_watc_user_id_691dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='watchhistory',
            index=models.Index(fields=['movie', '-started_at'], name='movies_watc_movie_i_783876_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['user', 'status', '-priority'], name='movies_watc_user_id_a2ae41_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['user', '-added_at'], name='movies_watc_user_id_e9443e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'movie')},
        ),
    ]
