# Generated by Django 5.0.1 on 2025-08-12 14:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKeyManager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_key', models.TextField()),
                ('key_name', models.CharField(default='OMDB API', max_length=100)),
                ('daily_limit', models.IntegerField(default=1000)),
                ('requests_today', models.IntegerField(default=0)),
                ('last_reset_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_patron', models.BooleanField(default=False, help_text='Patron status for poster API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
            },
        ),
        migrations.CreateModel(
            name='OMDBCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cache_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('cache_type', models.CharField(choices=[('search', 'Search Results'), ('detail', 'Movie Details'), ('poster', 'Poster Data')], max_length=20)),
                ('query_params', models.JSONField()),
                ('response_data', models.JSONField()),
                ('response_status', models.IntegerField(default=200)),
                ('hit_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['cache_type', '-updated_at'], name='movies_omdb_cache_t_8501c0_idx'), models.Index(fields=['expires_at'], name='movies_omdb_expires_712e47_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('search', 'Search'), ('detail', 'Movie Details'), ('poster', 'Poster')], max_length=20)),
                ('query_params', models.JSONField()),
                ('response_status', models.IntegerField()),
                ('response_time_ms', models.IntegerField()),
                ('from_cache', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='omdb_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', '-requested_at'], name='movies_apiu_user_id_a8b35a_idx'), models.Index(fields=['request_type', '-requested_at'], name='movies_apiu_request_06c624_idx'), models.Index(fields=['from_cache', '-requested_at'], name='movies_apiu_from_ca_28436f_idx')],
            },
        ),
        migrations.CreateModel(
            name='MovieImportQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imdb_id', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='movies_movi_status_b9202f_idx')],
            },
        ),
    ]
