# Generated by Django 5.0.1 on 2025-08-12 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_apikeymanager_omdbcache_apiusagelog_movieimportqueue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIKeyManager',
        ),
        migrations.RemoveField(
            model_name='apiusagelog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='movieimportqueue',
            name='requested_by',
        ),
        migrations.DeleteModel(
            name='OMDBCache',
        ),
        migrations.DeleteModel(
            name='APIUsageLog',
        ),
        migrations.DeleteModel(
            name='MovieImportQueue',
        ),
    ]
