# Generated by Django 5.2.9 on 2025-12-05 19:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_type', models.CharField(choices=[('direct', 'Direct Message'), ('group', 'Group Chat'), ('channel', 'Channel (broadcast)')], default='direct', max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='messenger/avatars/')),
                ('is_encrypted', models.BooleanField(default=True, help_text='End-to-end encryption enabled')),
                ('encryption_version', models.PositiveIntegerField(default=1)),
                ('transport_mode', models.CharField(choices=[('hub', 'Hub Relay (server-based)'), ('p2p', 'P2P Direct (peer-to-peer)'), ('hybrid', 'Hybrid (P2P with Hub fallback)')], default='hub', max_length=20)),
                ('p2p_enabled', models.BooleanField(default=False, help_text='Allow P2P connections')),
                ('group_key_version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messenger_conversations',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', 'Text Message'), ('image', 'Image'), ('file', 'File Attachment'), ('voice', 'Voice Message'), ('video', 'Video'), ('location', 'Location'), ('system', 'System Message')], default='text', max_length=20)),
                ('encrypted_content', models.TextField(help_text='AES-256-GCM encrypted message content')),
                ('content_nonce', models.CharField(help_text='Encryption nonce (Base64)', max_length=50)),
                ('signature', models.TextField(help_text='Ed25519 signature for message verification')),
                ('encryption_version', models.PositiveIntegerField(default=1)),
                ('sender_key_id', models.UUIDField(help_text="Sender's encryption key ID used")),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('original_content_hash', models.CharField(blank=True, max_length=64)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_for_everyone', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_via', models.CharField(choices=[('hub', 'Hub'), ('p2p', 'P2P')], default='hub', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_message_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messenger.conversation')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='messenger.message')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('thread_root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_messages', to='messenger.message')),
            ],
            options={
                'db_table': 'messenger_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='messenger/attachments/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveBigIntegerField()),
                ('encrypted_file_key', models.TextField(help_text='AES key for file, encrypted with message key')),
                ('file_nonce', models.CharField(max_length=50)),
                ('file_hash', models.CharField(help_text='SHA-256 hash of encrypted file', max_length=128)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='messenger/thumbnails/%Y/%m/')),
                ('encrypted_thumbnail_key', models.TextField(blank=True)),
                ('encrypted_metadata', models.TextField(blank=True, help_text='Encrypted JSON with width, height, duration, etc.')),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='messenger.message')),
            ],
            options={
                'db_table': 'messenger_attachments',
            },
        ),
        migrations.CreateModel(
            name='MessageDeliveryQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=5)),
                ('last_retry_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_queue', to='messenger.message')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messenger_delivery_queue',
                'ordering': ['queued_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emoji', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='messenger.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messenger_reactions',
            },
        ),
        migrations.CreateModel(
            name='MessageReadReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='messenger.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messenger_read_receipts',
            },
        ),
        migrations.CreateModel(
            name='P2PSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('initiating', 'Initiating'), ('connecting', 'Connecting'), ('connected', 'Connected'), ('disconnected', 'Disconnected'), ('failed', 'Failed')], default='initiating', max_length=20)),
                ('connection_info', models.JSONField(default=dict)),
                ('session_key_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('messages_received', models.PositiveIntegerField(default=0)),
                ('bytes_transferred', models.PositiveBigIntegerField(default=0)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p2p_sessions', to='messenger.conversation')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2p_sessions_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2p_sessions_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messenger_p2p_sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('encrypted_group_key', models.TextField(blank=True, help_text="Group encryption key encrypted with participant's public key")),
                ('group_key_version', models.PositiveIntegerField(default=1)),
                ('public_key_id', models.UUIDField(blank=True, null=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('muted_until', models.DateTimeField(blank=True, null=True)),
                ('notification_sound', models.CharField(default='default', max_length=50)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('last_read_message_id', models.UUIDField(blank=True, null=True)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('p2p_preferred', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='messenger.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messenger_participants',
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='UserEncryptionKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, max_length=100)),
                ('device_name', models.CharField(blank=True, max_length=200)),
                ('public_key', models.TextField(help_text='X25519 public key (Base64)')),
                ('encrypted_private_key', models.TextField(help_text="X25519 private key encrypted with user's key derivation (Base64)")),
                ('signing_public_key', models.TextField(help_text='Ed25519 public key for message signing (Base64)')),
                ('encrypted_signing_private_key', models.TextField(help_text='Ed25519 private key encrypted (Base64)')),
                ('key_version', models.PositiveIntegerField(default=1)),
                ('algorithm', models.CharField(default='X25519+Ed25519', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encryption_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messenger_user_encryption_keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['conversation_type', 'is_active'], name='messenger_c_convers_01951a_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['created_by'], name='messenger_c_created_a15236_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['last_message_at'], name='messenger_c_last_me_83c0e2_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='messenger_m_convers_6e6b5e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='messenger_m_sender__b60e62_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['reply_to'], name='messenger_m_reply_t_1e02df_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['client_message_id'], name='messenger_m_client__31decc_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['expires_at'], name='messenger_m_expires_6a7bcc_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['message'], name='messenger_a_message_67c59c_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['file_type'], name='messenger_a_file_ty_42d46f_idx'),
        ),
        migrations.AddIndex(
            model_name='messagedeliveryqueue',
            index=models.Index(fields=['recipient', 'status'], name='messenger_d_recipie_46e18d_idx'),
        ),
        migrations.AddIndex(
            model_name='messagedeliveryqueue',
            index=models.Index(fields=['status', 'next_retry_at'], name='messenger_d_status_787186_idx'),
        ),
        migrations.AddIndex(
            model_name='messagedeliveryqueue',
            index=models.Index(fields=['expires_at'], name='messenger_d_expires_38493b_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['message'], name='messenger_r_message_30938f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereaction',
            unique_together={('message', 'user', 'emoji')},
        ),
        migrations.AddIndex(
            model_name='messagereadreceipt',
            index=models.Index(fields=['message'], name='messenger_r_message_4735ac_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereadreceipt',
            index=models.Index(fields=['user', 'read_at'], name='messenger_r_user_id_c0bb4d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereadreceipt',
            unique_together={('message', 'user')},
        ),
        migrations.AddIndex(
            model_name='p2psession',
            index=models.Index(fields=['user1', 'user2', 'status'], name='messenger_p_user1_i_2da3e8_idx'),
        ),
        migrations.AddIndex(
            model_name='p2psession',
            index=models.Index(fields=['status'], name='messenger_p_status_a86804_idx'),
        ),
        migrations.AddIndex(
            model_name='p2psession',
            index=models.Index(fields=['last_activity'], name='messenger_p_last_ac_3f709f_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['user', 'is_active'], name='messenger_p_user_id_09b89c_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['conversation', 'is_active'], name='messenger_p_convers_c59482_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['last_read_at'], name='messenger_p_last_re_d538dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('conversation', 'user')},
        ),
        migrations.AddIndex(
            model_name='userencryptionkey',
            index=models.Index(fields=['user', 'is_active'], name='messenger_u_user_id_bdc541_idx'),
        ),
        migrations.AddIndex(
            model_name='userencryptionkey',
            index=models.Index(fields=['device_id'], name='messenger_u_device__9d4015_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userencryptionkey',
            unique_together={('user', 'device_id')},
        ),
    ]
