# Generated by Django 5.1.3 on 2025-12-05
# UserOfflineCache model for offline authentication

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOfflineCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('global_uuid', models.UUIDField(db_index=True, unique=True)),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('offline_hash', models.CharField(max_length=128)),
                ('cached_permissions', models.JSONField(default=dict)),
                ('cached_roles', models.JSONField(default=list)),
                ('cached_at', models.DateTimeField(auto_now=True)),
                ('cache_valid_until', models.DateTimeField()),
                ('last_synced_with_hub', models.DateTimeField(blank=True, null=True)),
                ('hub_url', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'auth_user_offline_cache',
                'ordering': ['-cached_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userofflinecache',
            index=models.Index(fields=['username'], name='auth_cache_user_idx'),
        ),
        migrations.AddIndex(
            model_name='userofflinecache',
            index=models.Index(fields=['email'], name='auth_cache_email_idx'),
        ),
        migrations.AddIndex(
            model_name='userofflinecache',
            index=models.Index(fields=['cache_valid_until'], name='auth_cache_valid_idx'),
        ),
    ]
