# Generated by Django 5.2.9 on 2025-12-05 16:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userofflinecache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_user_uuid', models.UUIDField(db_index=True, unique=True)),
                ('hub_username', models.CharField(max_length=150)),
                ('hub_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('active', 'Active'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('verification_code', models.CharField(blank=True, max_length=6)),
                ('verification_expires', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('hub_url', models.URLField()),
                ('last_permission_sync', models.DateTimeField(blank=True, null=True)),
                ('synced_permissions', models.JSONField(default=list)),
                ('synced_roles', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_by', models.CharField(choices=[('user', 'User Initiated'), ('admin', 'Admin Initiated'), ('auto', 'Auto-detected')], default='user', max_length=20)),
            ],
            options={
                'db_table': 'auth_account_links',
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('verification_type', models.CharField(choices=[('registration', 'New Registration'), ('change', 'Email Change'), ('recovery', 'Account Recovery')], default='registration', max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auth_email_verification_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HubKeyPair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('key_name', models.CharField(max_length=100)),
                ('key_type', models.CharField(choices=[('jwt', 'JWT Signing'), ('node', 'Node Authentication'), ('export', 'Data Export Signing')], default='jwt', max_length=20)),
                ('public_key', models.TextField()),
                ('private_key', models.TextField(blank=True)),
                ('algorithm', models.CharField(default='RS256', max_length=20)),
                ('key_size', models.IntegerField(default=2048)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'auth_hub_key_pairs',
                'ordering': ['-created_at'],
            },
        ),
        # Note: RenameIndex operations removed - indexes already exist with new names
        # after database restore from backup
        migrations.AddField(
            model_name='accountlink',
            name='local_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hub_link', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='hubkeypair',
            index=models.Index(fields=['key_id'], name='auth_hub_ke_key_id_bcc5dc_idx'),
        ),
        migrations.AddIndex(
            model_name='hubkeypair',
            index=models.Index(fields=['key_type', 'is_active'], name='auth_hub_ke_key_typ_6eaa91_idx'),
        ),
        migrations.AddIndex(
            model_name='hubkeypair',
            index=models.Index(fields=['is_primary'], name='auth_hub_ke_is_prim_4ea71e_idx'),
        ),
        migrations.AddIndex(
            model_name='accountlink',
            index=models.Index(fields=['hub_user_uuid'], name='auth_accoun_hub_use_0bfb5e_idx'),
        ),
        migrations.AddIndex(
            model_name='accountlink',
            index=models.Index(fields=['status'], name='auth_accoun_status_c9165b_idx'),
        ),
        migrations.AddIndex(
            model_name='accountlink',
            index=models.Index(fields=['hub_email'], name='auth_accoun_hub_ema_113d4f_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverificationtoken',
            index=models.Index(fields=['token'], name='auth_email__token_247a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverificationtoken',
            index=models.Index(fields=['user', 'is_used'], name='auth_email__user_id_7698c8_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverificationtoken',
            index=models.Index(fields=['expires_at'], name='auth_email__expires_8a24ed_idx'),
        ),
    ]
