# Generated by Django 5.0.1 on 2025-08-12 00:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spotify_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('popularity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('followers', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('bio', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('formed_year', models.IntegerField(blank=True, null=True)),
                ('spotify_url', models.URLField(blank=True, max_length=500)),
                ('website_url', models.URLField(blank=True, max_length=500)),
                ('spotify_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_spotify_sync', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-popularity', 'name'],
                'indexes': [models.Index(fields=['name'], name='music_artis_name_e97718_idx'), models.Index(fields=['slug'], name='music_artis_slug_38018e_idx'), models.Index(fields=['-popularity'], name='music_artis_popular_433f53_idx')],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spotify_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('album_type', models.CharField(choices=[('album', 'album'), ('single', 'single'), ('compilation', 'compilation'), ('ep', 'ep')], default='album', max_length=20)),
                ('release_date', models.DateField(blank=True, db_index=True, null=True)),
                ('total_tracks', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0, help_text='Total duration in milliseconds')),
                ('cover_url', models.URLField(blank=True, max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('popularity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('spotify_url', models.URLField(blank=True, max_length=500)),
                ('spotify_data', models.JSONField(blank=True, default=dict)),
                ('artwork_file', models.FileField(blank=True, null=True, upload_to='music/artwork/')),
                ('artwork_source', models.CharField(blank=True, help_text='Source of open artwork', max_length=200)),
                ('artwork_license', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_spotify_sync', models.DateTimeField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music.artist')),
                ('featured_artists', models.ManyToManyField(blank=True, related_name='featured_albums', to='music.artist')),
            ],
            options={
                'ordering': ['-release_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ListeningStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly')], max_length=20)),
                ('period_date', models.DateField()),
                ('total_tracks_played', models.IntegerField(default=0)),
                ('unique_tracks_played', models.IntegerField(default=0)),
                ('total_time_ms', models.BigIntegerField(default=0)),
                ('top_tracks', models.JSONField(default=list)),
                ('top_artists', models.JSONField(default=list)),
                ('top_albums', models.JSONField(default=list)),
                ('top_genres', models.JSONField(default=list)),
                ('peak_hour', models.IntegerField(blank=True, null=True)),
                ('device_breakdown', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_date'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('private', 'private'), ('public', 'public'), ('collaborative', 'collaborative')], default='private', max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='playlists/')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('play_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborative_playlists', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spotify_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('isrc', models.CharField(blank=True, db_index=True, help_text='International Standard Recording Code', max_length=20, null=True)),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('track_number', models.IntegerField(default=1)),
                ('disc_number', models.IntegerField(default=1)),
                ('duration_ms', models.IntegerField(help_text='Duration in milliseconds')),
                ('explicit', models.BooleanField(default=False)),
                ('popularity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('acousticness', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('danceability', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('energy', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('instrumentalness', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('key', models.IntegerField(blank=True, null=True)),
                ('liveness', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('loudness', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mode', models.IntegerField(blank=True, null=True)),
                ('speechiness', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('tempo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('time_signature', models.IntegerField(blank=True, null=True)),
                ('valence', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('spotify_url', models.URLField(blank=True, max_length=500)),
                ('preview_url', models.URLField(blank=True, help_text='30-second preview URL', max_length=500)),
                ('spotify_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.artist')),
                ('featured_artists', models.ManyToManyField(blank=True, related_name='featured_tracks', to='music.artist')),
            ],
            options={
                'ordering': ['album', 'disc_number', 'track_number'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.track')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(related_name='in_playlists', through='music.PlaylistTrack', to='music.track'),
        ),
        migrations.CreateModel(
            name='ListeningHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('duration_played_ms', models.IntegerField(help_text='How long the track was played')),
                ('completed', models.BooleanField(default=False, help_text='Was the track played to completion')),
                ('skipped', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, help_text='Playlist, album, search, etc.', max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_history', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_history', to='music.track')),
            ],
            options={
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('play_count', models.IntegerField(default=0)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album')),
            ],
            options={
                'ordering': ['-is_favorite', '-added_at'],
            },
        ),
        migrations.CreateModel(
            name='UserArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('play_count', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.artist')),
            ],
            options={
                'ordering': ['-is_favorite', '-play_count'],
            },
        ),
        migrations.CreateModel(
            name='UserLibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spotify_connected', models.BooleanField(default=False)),
                ('spotify_user_id', models.CharField(blank=True, max_length=100)),
                ('auto_sync', models.BooleanField(default=True)),
                ('total_play_time_ms', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('albums', models.ManyToManyField(related_name='in_libraries', through='music.UserAlbum', to='music.album')),
                ('artists', models.ManyToManyField(related_name='in_libraries', through='music.UserArtist', to='music.artist')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='music_library', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user libraries',
            },
        ),
        migrations.AddField(
            model_name='userartist',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.userlibrary'),
        ),
        migrations.AddField(
            model_name='useralbum',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.userlibrary'),
        ),
        migrations.CreateModel(
            name='UserTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('play_count', models.IntegerField(default=0)),
                ('skip_count', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.userlibrary')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.track')),
            ],
            options={
                'ordering': ['-is_favorite', '-play_count'],
            },
        ),
        migrations.AddField(
            model_name='userlibrary',
            name='tracks',
            field=models.ManyToManyField(related_name='in_libraries', through='music.UserTrack', to='music.track'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['name', 'artist'], name='music_album_name_1c7496_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['-release_date'], name='music_album_release_31abd8_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['-popularity'], name='music_album_popular_cb53d5_idx'),
        ),
        migrations.AddIndex(
            model_name='listeningstats',
            index=models.Index(fields=['user', 'period', '-period_date'], name='music_liste_user_id_a3211e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listeningstats',
            unique_together={('user', 'period', 'period_date')},
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['name'], name='music_track_name_8748ed_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['album', 'track_number'], name='music_track_album_i_7ec3a1_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['-popularity'], name='music_track_popular_375f1b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('album', 'disc_number', 'track_number')},
        ),
        migrations.AlterUniqueTogether(
            name='playlisttrack',
            unique_together={('playlist', 'track', 'position')},
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['user', '-updated_at'], name='music_playl_user_id_ab4a82_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['visibility', '-created_at'], name='music_playl_visibil_76eed7_idx'),
        ),
        migrations.AddIndex(
            model_name='listeninghistory',
            index=models.Index(fields=['user', '-played_at'], name='music_liste_user_id_9e039b_idx'),
        ),
        migrations.AddIndex(
            model_name='listeninghistory',
            index=models.Index(fields=['track', '-played_at'], name='music_liste_track_i_c99f29_idx'),
        ),
        migrations.AddIndex(
            model_name='listeninghistory',
            index=models.Index(fields=['user', 'track', '-played_at'], name='music_liste_user_id_6ead05_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userartist',
            unique_together={('library', 'artist')},
        ),
        migrations.AlterUniqueTogether(
            name='useralbum',
            unique_together={('library', 'album')},
        ),
        migrations.AlterUniqueTogether(
            name='usertrack',
            unique_together={('library', 'track')},
        ),
    ]
