# Generated by Django 5.0.1 on 2025-11-12 21:25

import modules.music.backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artwork_file',
            field=models.FileField(blank=True, null=True, upload_to=modules.music.backend.models.music_artwork_path),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=modules.music.backend.models.playlist_cover_path),
        ),
    ]
