# Generated by Django 5.0.1 on 2025-08-08 15:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_ai_confidence_document_ai_parsed_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('challenge_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('special', 'Special Event')], max_length=30)),
                ('target_count', models.IntegerField(default=1)),
                ('target_type', models.CharField(choices=[('receipts_processed', 'Process Receipts'), ('receipts_validated', 'Validate Receipts'), ('accuracy_target', 'Accuracy Target'), ('streak_days', 'Maintain Streak'), ('points_earned', 'Earn Points')], max_length=50)),
                ('points_reward', models.IntegerField(default=100)),
                ('badge_reward', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LearningModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('store_name', 'Store Name Pattern'), ('date_format', 'Date Format Pattern'), ('amount_format', 'Amount Format Pattern'), ('item_pattern', 'Item Pattern'), ('field_location', 'Field Location Pattern')], max_length=50)),
                ('pattern_value', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('usage_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('store_name', models.CharField(blank=True, max_length=255)),
                ('sample_text', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-confidence_score', '-usage_count'],
                'indexes': [models.Index(fields=['pattern_type', '-confidence_score'], name='documents_l_pattern_a47375_idx'), models.Index(fields=['store_name', 'pattern_type'], name='documents_l_store_n_e932a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(choices=[('earned', 'Earned'), ('spent', 'Spent'), ('bonus', 'Bonus'), ('penalty', 'Penalty')], max_length=20)),
                ('related_document_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('current_level', models.IntegerField(default=1)),
                ('experience_points', models.IntegerField(default=0)),
                ('receipts_processed', models.IntegerField(default=0)),
                ('receipts_validated', models.IntegerField(default=0)),
                ('accuracy_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('streak_days', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('weekly_rank', models.IntegerField(blank=True, null=True)),
                ('monthly_rank', models.IntegerField(blank=True, null=True)),
                ('all_time_rank', models.IntegerField(blank=True, null=True)),
                ('preferred_language', models.CharField(default='tr', max_length=10)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('tutorial_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_points'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('first_receipt', 'First Receipt'), ('accuracy_master', 'Accuracy Master'), ('speed_demon', 'Speed Demon'), ('validator', 'Validator'), ('contributor', 'Contributor'), ('streak', 'Streak Keeper'), ('level_up', 'Level Up'), ('milestone', 'Milestone'), ('special', 'Special Event')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='star', max_length=50)),
                ('color', models.CharField(default='#FFD700', max_length=7)),
                ('points_awarded', models.IntegerField(default=0)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField(blank=True, null=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('receipts_processed', models.IntegerField(default=0)),
                ('accuracy_score', models.FloatField(default=0.0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-points_earned'],
                'indexes': [models.Index(fields=['period_type', '-points_earned'], name='documents_l_period__091291_idx'), models.Index(fields=['period_start', 'period_end'], name='documents_l_period__9d0dfa_idx')],
                'unique_together': {('user', 'period_type', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_progress', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_reward', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='documents.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('user', 'challenge')},
            },
        ),
        migrations.CreateModel(
            name='ValidationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.UUIDField()),
                ('field_name', models.CharField(max_length=50)),
                ('original_value', models.TextField(blank=True)),
                ('corrected_value', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('votes_up', models.IntegerField(default=0)),
                ('votes_down', models.IntegerField(default=0)),
                ('points_awarded', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document_id', 'field_name'], name='documents_v_documen_0adb64_idx'), models.Index(fields=['user', '-created_at'], name='documents_v_user_id_7e2231_idx')],
            },
        ),
    ]
