# Generated by Django 5.0.1 on 2025-08-08 23:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_challenge_learningmodel_pointtransaction_userprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('financial', 'Financial'), ('medical', 'Medical'), ('legal', 'Legal'), ('personal', 'Personal'), ('government', 'Government'), ('education', 'Education'), ('business', 'Business'), ('utility', 'Utility'), ('retail', 'Retail'), ('transportation', 'Transportation')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.JSONField(default=list, help_text='Keywords to detect this document type')),
                ('regex_patterns', models.JSONField(default=list, help_text='Regex patterns for detection')),
                ('requires_ocr', models.BooleanField(default=True)),
                ('requires_validation', models.BooleanField(default=False)),
                ('privacy_level', models.IntegerField(default=1, help_text='1=Public, 2=Private, 3=Restricted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_type', models.CharField(choices=[('user', 'Individual User'), ('group', 'User Group'), ('public', 'Public Link'), ('restricted', 'Restricted Access')], default='user', max_length=20)),
                ('shared_with_group', models.CharField(blank=True, help_text='Group name if sharing with group', max_length=100)),
                ('permission', models.CharField(choices=[('view', 'View Only'), ('comment', 'View and Comment'), ('edit', 'View and Edit'), ('admin', 'Full Access')], default='view', max_length=20)),
                ('can_reshare', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('share_link', models.CharField(blank=True, max_length=100, unique=True)),
                ('access_count', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='documents.document')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_shared', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('document', 'shared_with'), ('document', 'shared_with_group')},
            },
        ),
    ]
