# Generated by Django 5.0.1 on 2025-11-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_documenttype_documentshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('unknown', 'Unknown (Auto-detect)'), ('receipt', 'Receipt/Fiş'), ('invoice', 'Invoice/Fatura'), ('bank_statement', 'Bank Statement'), ('cc_statement', 'Credit Card Statement'), ('contract', 'Contract/Sözleşme'), ('other', 'Other')], default='receipt', max_length=20),
        ),
    ]
