# Generated by Django 5.0.1 on 2025-11-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('manual_review', 'Manual Review Needed')], default='processing', max_length=20),
        ),
    ]
