# Generated by Django 5.0.1 on 2025-11-12 21:25

import modules.documents.backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_document_analysis_results_document_last_analysis_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.FileField(upload_to=modules.documents.backend.models.document_upload_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='thumbnail_path',
            field=models.FileField(blank=True, null=True, upload_to=modules.documents.backend.models.document_thumbnail_path),
        ),
    ]
