# Generated by Django 5.0.1 on 2025-08-12 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolitaireSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('stock_pile', models.JSONField(default=list)),
                ('waste_pile', models.JSONField(default=list)),
                ('foundation_piles', models.JSONField(default=dict)),
                ('tableau_piles', models.JSONField(default=list)),
                ('moves_count', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('game_time', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_won', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('last_minimize', models.DateTimeField(blank=True, null=True)),
                ('lock_password', models.CharField(blank=True, max_length=128, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solitaire_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_played'],
            },
        ),
        migrations.CreateModel(
            name='SolitaireMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField()),
                ('from_pile', models.CharField(max_length=20)),
                ('to_pile', models.CharField(max_length=20)),
                ('cards_moved', models.JSONField()),
                ('cards_revealed', models.JSONField(default=list)),
                ('previous_state', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='solitaire.solitairesession')),
            ],
            options={
                'ordering': ['session', 'move_number'],
            },
        ),
        migrations.CreateModel(
            name='SolitaireStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.IntegerField(default=0)),
                ('games_won', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('highest_score', models.IntegerField(default=0)),
                ('total_time_played', models.IntegerField(default=0)),
                ('current_win_streak', models.IntegerField(default=0)),
                ('best_win_streak', models.IntegerField(default=0)),
                ('fastest_win', models.IntegerField(blank=True, null=True)),
                ('fewest_moves_win', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solitaire_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Solitaire statistics',
            },
        ),
        migrations.AddIndex(
            model_name='solitairesession',
            index=models.Index(fields=['user', 'is_active'], name='solitaire_s_user_id_351ba4_idx'),
        ),
        migrations.AddIndex(
            model_name='solitairesession',
            index=models.Index(fields=['session_id'], name='solitaire_s_session_8a1531_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='solitairemove',
            unique_together={('session', 'move_number')},
        ),
    ]
