# Generated by Django 5.0.1 on 2025-08-14 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solitaire', '0002_solitaireplayer_solitairegamesession_solitaireactivity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='solitaireactivity',
            new_name='solitaire_s_session_b83e8d_idx',
            old_name='solitaire_s_session_f0e3e1_idx',
        ),
        migrations.RenameIndex(
            model_name='solitaireactivity',
            new_name='solitaire_s_timesta_e183f9_idx',
            old_name='solitaire_s_timesta_c8e5e4_idx',
        ),
        migrations.RenameIndex(
            model_name='solitairegamesession',
            new_name='solitaire_s_player__689a8a_idx',
            old_name='solitaire_s_player__c0e8e9_idx',
        ),
        migrations.RenameIndex(
            model_name='solitairegamesession',
            new_name='solitaire_s_is_won_7286d0_idx',
            old_name='solitaire_s_is_won_58e8a5_idx',
        ),
        migrations.RenameIndex(
            model_name='solitaireplayer',
            new_name='solitaire_s_session_e16dc2_idx',
            old_name='solitaire_s_session_cc5e15_idx',
        ),
        migrations.RenameIndex(
            model_name='solitaireplayer',
            new_name='solitaire_s_last_se_b4b7c3_idx',
            old_name='solitaire_s_last_se_6b1f8e_idx',
        ),
    ]
