# Generated by Django 5.0.1 on 2025-08-07 17:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=50)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_vector', models.JSONField(blank=True, default=list, help_text='Search keywords for this product')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('store_type', models.CharField(choices=[('supermarket', 'Supermarket'), ('market', 'Local Market'), ('bazaar', 'Bazaar'), ('online', 'Online Store'), ('other', 'Other')], max_length=50)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PersonalBasket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Ana Sepet', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('calculation_period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personal_baskets',
            },
        ),
        migrations.CreateModel(
            name='InflationReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('report_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom Period')], max_length=20)),
                ('inflation_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('total_start_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_end_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category_breakdown', models.JSONField(default=dict)),
                ('official_inflation_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('detailed_data', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inflation_reports', to=settings.AUTH_USER_MODEL)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_inflation.personalbasket')),
            ],
            options={
                'db_table': 'inflation_reports',
                'ordering': ['-period_end', '-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('price_drop', 'Price Drop'), ('price_increase', 'Price Increase'), ('threshold', 'Price Threshold')], max_length=20)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentage_change', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('trigger_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_inflation.product')),
            ],
            options={
                'db_table': 'price_alerts',
            },
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20)),
                ('custom_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Custom weight in basket (%)', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='personal_inflation.personalbasket')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_inflation.product')),
            ],
            options={
                'db_table': 'basket_items',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('official_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Official weight in CPI basket (%)', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='personal_inflation.productcategory')),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'db_table': 'product_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='personal_inflation.productcategory'),
        ),
        migrations.CreateModel(
            name='PriceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='TRY', max_length=3)),
                ('is_discounted', models.BooleanField(default=False)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('source', models.CharField(choices=[('user', 'User Input'), ('crowdsource', 'Crowdsourced'), ('official', 'Official Data'), ('scraper', 'Web Scraper')], default='user', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('receipt_image', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_records', to='personal_inflation.product')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal_inflation.store')),
            ],
            options={
                'db_table': 'price_records',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='personalbasket',
            index=models.Index(fields=['user', 'is_active', 'is_default'], name='personal_ba_user_id_de515a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='personalbasket',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='inflationreport',
            index=models.Index(fields=['user', 'period_end'], name='inflation_r_user_id_4d957a_idx'),
        ),
        migrations.AddIndex(
            model_name='inflationreport',
            index=models.Index(fields=['basket', 'period_end'], name='inflation_r_basket__f82de0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inflationreport',
            unique_together={('user', 'basket', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='pricealert',
            index=models.Index(fields=['user', 'is_active'], name='price_alert_user_id_600b95_idx'),
        ),
        migrations.AddIndex(
            model_name='pricealert',
            index=models.Index(fields=['product', 'is_active'], name='price_alert_product_621c32_idx'),
        ),
        migrations.AddIndex(
            model_name='basketitem',
            index=models.Index(fields=['basket', 'is_active'], name='basket_item_basket__6a0e70_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='basketitem',
            unique_together={('basket', 'product')},
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['parent', 'is_active'], name='product_cat_parent__85b6f5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='products_categor_9e60b3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='products_barcode_d008ac_idx'),
        ),
        migrations.AddIndex(
            model_name='pricerecord',
            index=models.Index(fields=['product', 'recorded_at'], name='price_recor_product_6111ea_idx'),
        ),
        migrations.AddIndex(
            model_name='pricerecord',
            index=models.Index(fields=['store', 'recorded_at'], name='price_recor_store_i_967808_idx'),
        ),
        migrations.AddIndex(
            model_name='pricerecord',
            index=models.Index(fields=['recorded_at'], name='price_recor_recorde_dc6528_idx'),
        ),
        migrations.AddIndex(
            model_name='pricerecord',
            index=models.Index(fields=['user', 'created_at'], name='price_recor_user_id_24a800_idx'),
        ),
    ]
