# Generated by Django 5.0.1 on 2025-11-12 21:25
# Modified to handle JSONB to ArrayField conversion

import django.contrib.postgres.fields
import modules.personal_inflation.backend.models
from django.db import migrations, models


def convert_search_vector(apps, schema_editor):
    """
    Custom migration to convert search_vector from JSONB to ArrayField.
    PostgreSQL cannot directly cast JSONB to varchar[], so we need to:
    1. Create a temporary column
    2. Convert the data
    3. Drop the old column
    4. Rename the temporary column
    """
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            # Add temporary column
            cursor.execute("""
                ALTER TABLE products
                ADD COLUMN search_vector_temp varchar(200)[] DEFAULT '{}'
            """)

            # Convert JSONB arrays to PostgreSQL arrays
            # Handle both array and non-array JSONB values
            cursor.execute("""
                UPDATE products
                SET search_vector_temp = CASE
                    WHEN jsonb_typeof(search_vector) = 'array' THEN
                        ARRAY(SELECT jsonb_array_elements_text(search_vector))
                    ELSE
                        '{}'
                END
            """)

            # Drop old column
            cursor.execute("ALTER TABLE products DROP COLUMN search_vector")

            # Rename temporary column
            cursor.execute("""
                ALTER TABLE products
                RENAME COLUMN search_vector_temp TO search_vector
            """)


def reverse_search_vector(apps, schema_editor):
    """
    Reverse migration: Convert ArrayField back to JSONB
    """
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            # Add temporary JSONB column
            cursor.execute("""
                ALTER TABLE products
                ADD COLUMN search_vector_temp jsonb DEFAULT '[]'::jsonb
            """)

            # Convert array back to JSONB
            cursor.execute("""
                UPDATE products
                SET search_vector_temp = to_jsonb(search_vector)
            """)

            # Drop array column
            cursor.execute("ALTER TABLE products DROP COLUMN search_vector")

            # Rename temporary column
            cursor.execute("""
                ALTER TABLE products
                RENAME COLUMN search_vector_temp TO search_vector
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('personal_inflation', '0001_initial'),
    ]

    operations = [
        # First, update the receipt_image field (no conversion needed)
        migrations.AlterField(
            model_name='pricerecord',
            name='receipt_image',
            field=models.FileField(blank=True, null=True, upload_to=modules.personal_inflation.backend.models.receipt_image_path),
        ),

        # Custom operation to convert search_vector from JSONB to ArrayField
        migrations.RunPython(
            convert_search_vector,
            reverse_code=reverse_search_vector,
        ),

        # Now apply the final field definition (Django state update only)
        # The actual database change was done in RunPython above
        migrations.AlterField(
            model_name='product',
            name='search_vector',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                default=list,
                size=None
            ),
        ),
    ]
