# Generated by Django 5.0.1 on 2025-11-12 21:25

import django.contrib.postgres.fields
import modules.personal_inflation.backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_inflation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerecord',
            name='receipt_image',
            field=models.FileField(blank=True, null=True, upload_to=modules.personal_inflation.backend.models.receipt_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='search_vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
