# Generated by Django 5.0.1 on 2025-11-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birlikteyiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='earthquakedatasource',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='earthquakedatasource',
            name='avg_response_time',
            field=models.FloatField(blank=True, help_text='Ortalama yanıt süresi (saniye)', null=True),
        ),
        migrations.AddField(
            model_name='earthquakedatasource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='earthquakedatasource',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthquakedatasource',
            name='fetch_interval_minutes',
            field=models.IntegerField(default=5, help_text='Kaç dakikada bir veri çekilecek'),
        ),
        migrations.AddField(
            model_name='earthquakedatasource',
            name='filter_max_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='earthquakedatasource',
            name='filter_max_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='earthquakedatasource',
            name='filter_min_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='earthquakedatasource',
            name='filter_min_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='earthquakedatasource',
            name='filter_region_name',
            field=models.CharField(blank=True, help_text='Örn: Türkiye, Küresel, vb.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='earthquakedatasource',
            name='last_error_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthquakedatasource',
            name='last_response_time',
            field=models.FloatField(blank=True, help_text='Son yanıt süresi (saniye)', null=True),
        ),
        migrations.AddField(
            model_name='earthquakedatasource',
            name='max_results',
            field=models.IntegerField(default=100, help_text='Maksimum sonuç sayısı'),
        ),
        migrations.AddField(
            model_name='earthquakedatasource',
            name='min_magnitude',
            field=models.DecimalField(decimal_places=1, default=2.5, help_text='Minimum deprem büyüklüğü', max_digits=3),
        ),
        migrations.AddField(
            model_name='earthquakedatasource',
            name='success_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='earthquakedatasource',
            name='total_earthquakes_fetched',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='earthquakedatasource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='earthquakedatasource',
            name='use_geographic_filter',
            field=models.BooleanField(default=False, help_text='Coğrafi filtreleme kullan'),
        ),
    ]
