# Generated by Django 5.0.1 on 2025-08-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restopos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='allergens',
            field=models.JSONField(blank=True, default=list, verbose_name=models.CharField(max_length=50)),
        ),
    ]
